version: '3.1'

services:
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USERNAME: "${PG_USER}"
      POSTGRES_DB: "${PG_DB}"
    ports:
      - "${PG_PORT}:5432"
